//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationTelephone
    {
        public int Id { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> TelephoneTypeId { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual TelephoneType TelephoneType { get; set; }
    }
}
