//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string AssignedToUserId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Step { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedByUserId { get; set; }
        public Nullable<decimal> HoursEstimated { get; set; }
        public Nullable<decimal> HoursSpent { get; set; }
        public Nullable<decimal> HoursBudget { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual Task Task { get; set; }
    }
}
