//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDocument
    {
        public int Id { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string DocumentId { get; set; }
        public string FileName { get; set; }
        public string PreviewText { get; set; }
        public string ContentType { get; set; }
        public string DocumentUrl { get; set; }
        public string Owners { get; set; }
        public string IconLink { get; set; }
        public string AlternateLink { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string FileSize { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
