//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskItem
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<bool> IsDone { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
